import test from 'node:test';
import assert from 'node:assert/strict';
import {Temporal} from '@js-temporal/polyfill';
import {buildSajuProfile} from '../lib/saju/buildSajuProfile';
import {normalizeBirth} from '../lib/saju/normalizeBirth';
import {lunarToSolar} from '../lib/saju/lunarConversion';
import {calculateTodayPillar} from '../lib/saju/calculateTodayPillar';
import {buildDaily} from '../lib/saju/daily';
import {dayMasterProfiles,interpretSaju} from '../lib/saju/interpret';
import {api} from '../server/worker';
import type {BirthInput,Pillar} from '../lib/saju/types';
const base:BirthInput={birthDate:'1990-05-15',birthTime:'09:30',calendarType:'solar'};
const make=(x:Partial<BirthInput>={})=>buildSajuProfile({...base,...x});
const ganji=(p:Pillar|null)=>p?p.stem.hanja+p.branch.hanja:null;
// Independently published fixture: github.com/urstory/manseryeok-js README.
test('solar fixture and structured output',()=>{const p=make();assert.deepEqual(Object.values(p.pillars).map(ganji),['庚午','辛巳','庚辰','辛巳']);assert.equal(p.dayMaster?.hanja,'庚');assert.equal(Object.values(p.fiveElements).reduce((a,b)=>a+b),100);assert.equal(p.yinYang.yin+p.yinYang.yang,100);});
test('unknown time excludes hour and preserves valid day',()=>{const p=make({birthTime:null,timeUnknown:true});assert.equal(p.pillars.hour,null);assert.equal(ganji(p.pillars.day),'庚辰');assert.equal(Object.values(p.fiveElements).reduce((a,b)=>a+b),100)});
// KASI 2025 calendar announcement: lunar 1/1 = Jan 29, 8/15 = Oct 6.
test('Korean lunar conversion including leap month and equivalence',()=>{assert.equal(lunarToSolar('2025-01-01'),'2025-01-29');assert.equal(lunarToSolar('2025-08-15'),'2025-10-06');assert.equal(lunarToSolar('2025-06-01',true),'2025-07-25');assert.notEqual(lunarToSolar('2025-06-01'),lunarToSolar('2025-06-01',true));assert.deepEqual(make({birthDate:'2025-01-01',calendarType:'lunar'}).pillars,make({birthDate:'2025-01-29'}).pillars);assert.throws(()=>lunarToSolar('2024-06-01',true));});
test('explicit midnight vs 23:00 boundary and hour stems',()=>{assert.equal(ganji(make({birthTime:'22:59'}).pillars.day),'庚辰');assert.equal(ganji(make({birthTime:'23:00'}).pillars.day),'庚辰');assert.equal(ganji(make({birthTime:'23:59'}).pillars.hour),'丙子');assert.equal(ganji(make({birthDate:'1990-05-16',birthTime:'00:00'}).pillars.day),'辛巳');assert.equal(ganji(make({birthDate:'1990-05-16',birthTime:'00:59'}).pillars.hour),'戊子');assert.equal(ganji(make({birthTime:'23:00',dayBoundary:'zi23'}).pillars.day),'辛巳');assert.equal(ganji(make({birthTime:'23:00',dayBoundary:'zi23'}).pillars.hour),'戊子');assert.equal(make({timeUnknown:true,dayBoundary:'zi23'}).dayMaster,null);});
// Fixed lunar-typescript 1.8.6 regression: 2024 Li Chun 16:27:07 UTC+08 = 17:27:07 Seoul.
test('solar term switches year/month by instant, not civil month',()=>{const a=make({birthDate:'2024-02-04',birthTime:'17:27'});const b=make({birthDate:'2024-02-04',birthTime:'17:28'});assert.equal(ganji(a.pillars.year),'癸卯');assert.equal(ganji(b.pillars.year),'甲辰');assert.equal(ganji(a.pillars.month),'乙丑');assert.equal(ganji(b.pillars.month),'丙寅');assert.deepEqual(a.pillars.year,make({birthDate:'2024-02-04',birthTime:'08:27',timezone:'UTC'}).pillars.year);const unknown=make({birthDate:'2024-02-04',timeUnknown:true});assert.equal(unknown.pillars.year,null);assert.equal(unknown.pillars.month,null);});
test('leap day, errors, future, invalid and ambiguous local time',()=>{assert.equal(make({birthDate:'2000-02-29'}).birth.solarDate,'2000-02-29');for(const x of [{birthDate:'2023-02-29'},{birthDate:'1990-13-01'},{birthDate:'1990-04-31'},{birthDate:'2099-01-01'},{birthTime:'24:00'},{birthTime:'12:60'},{timezone:'invalid'},{birthDate:'2024-03-10',birthTime:'02:30',timezone:'America/New_York'},{birthDate:'2024-11-03',birthTime:'01:30',timezone:'America/New_York'}])assert.throws(()=>make(x));assert.throws(()=>normalizeBirth({...base,birthDate:'2026-09-17'},Temporal.Instant.from('2026-09-16T00:00:00Z')));});
test('today is deterministic with 60-day cycle and date rollover',()=>{const a=calculateTodayPillar('1990-05-15');assert.equal(a.stem.hanja+a.branch.hanja,'庚辰');assert.deepEqual(calculateTodayPillar('1990-07-14').stem,a.stem);const p=make(),d=buildDaily(p,'2026-09-15');assert.deepEqual(buildDaily(p,'2026-09-15'),d);assert.notDeepEqual(buildDaily(p,'2026-09-16').today,d.today);assert.ok(d.scores.every(s=>s>=45&&s<=95));assert.equal(d.guide.goodThings.length,3);assert.ok(d.quote.reason);assert.ok(d.exercise.category);});
test('all ten profiles have complete gentle interpretation',()=>{assert.equal(Object.keys(dayMasterProfiles).length,10);const r=interpretSaju(make());assert.equal(r.strengths.length,3);assert.equal(r.cautions.length,3);assert.ok(Object.values(r).every(v=>typeof v==='string'?v.length>0:Array.isArray(v)&&v.length>0));});
const request=(path:string,body:unknown)=>new Request('https://test.local'+path,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});
test('API JSON, validation and client pillar tamper resistance',async()=>{const calc=await api(request('/api/saju/calculate',base));assert.equal(calc.status,200);assert.equal(calc.headers.get('cache-control'),'no-store');const p=await calc.json();p.dayMaster.hanja='甲';const r=await api(request('/api/saju/interpret',{sajuProfile:p}));assert.equal(r.status,200);assert.match((await r.json()).oneLineSummary,/금속/);const d=await api(request('/api/daily',{sajuProfile:p,date:'2026-09-15'}));assert.equal(d.status,200);assert.ok((await d.json()).overallScore>=45);assert.equal((await api(request('/api/saju/calculate',{...base,birthDate:'bad'}))).status,400);assert.equal((await api(new Request('https://test.local/api/daily'))).status,405);assert.equal((await api(request('/api/daily',{sajuProfile:p,date:'2026-02-30'}))).status,400);});
