"use client";
import {useEffect,useState} from 'react';
import {useRouter} from 'next/navigation';
import {ArrowRight,LockKeyhole} from 'lucide-react';
import {useEnergy} from './EnergyStore';
import {emptyProfile,type Profile} from '@/data/daily';
import {normalizeBirth} from '@/lib/saju/normalizeBirth';
import {toBirthInput,type ProfileInput} from '@/lib/saju/client';
export type Birth=ProfileInput;
export function validateBirth(b:Birth,calendar='solar'){try{normalizeBirth(toBirthInput({...b,calendar:calendar as 'solar'|'lunar'}));return ''}catch(e){return (e as Error).message}}
export function BirthOptions({profile:p,onChange}:{profile:Profile;onChange:(p:Profile)=>void}){return <div className="birth-options"><label>달력<select aria-label="달력 구분" value={p.calendar} onChange={e=>onChange({...p,calendar:e.target.value as Profile['calendar'],leapMonth:false})}><option value="solar">양력</option><option value="lunar">음력</option></select></label>{p.calendar==='lunar'&&<label className="simple-check"><input type="checkbox" checked={p.leapMonth||false} onChange={e=>onChange({...p,leapMonth:e.target.checked})}/>윤달</label>}<label>출생시간<input aria-label="출생시간" type="time" value={p.hour===''?'':`${p.hour.padStart(2,'0')}:${p.minute||'00'}`} onChange={e=>{const [hour,minute]=e.target.value.split(':');onChange({...p,hour:hour||'',minute:minute||'00'})}}/></label><label className="simple-check"><input type="checkbox" checked={p.hour===''} onChange={e=>onChange({...p,hour:e.target.checked?'':'12',minute:'00'})}/>시간 모름</label><details><summary>시간대·날짜 변경 기준</summary><label>출생지 시간대<input aria-label="출생지 시간대" value={p.timezone||'Asia/Seoul'} onChange={e=>onChange({...p,timezone:e.target.value})}/></label><label>하루가 바뀌는 시각<select aria-label="날짜 변경 기준" value={p.dayBoundary||'midnight'} onChange={e=>onChange({...p,dayBoundary:e.target.value as Profile['dayBoundary']})}><option value="midnight">00:00 자정 기준</option><option value="zi23">23:00 자시 시작 기준</option></select></label><small>기본은 한국 표준시와 자정 기준입니다. 진태양시 보정은 적용하지 않아요.</small></details></div>}
export function BirthDateForm({detailed=false,onResult}:{detailed?:boolean;onResult?:(b:Birth)=>void}){const e=useEnergy();const router=useRouter();const [birth,setBirth]=useState<Profile>(emptyProfile);const [error,setError]=useState('');useEffect(()=>{if(e.ready)setBirth(e.userProfile)},[e.ready,e.userProfile]);function submit(event:React.FormEvent){event.preventDefault();const issue=validateBirth(birth,birth.calendar);if(issue){setError(issue);return}if(!e.saveProfile(birth))return;setError('');if(onResult)onResult(birth);else router.push('/saju');}return <form onSubmit={submit} className="birth-form"><div className="form-label">생년월일을 입력해주세요 <span>1900년 이후</span></div><div className="birth-fields">{(['year','month','day'] as const).map((key,i)=><label key={key}><input aria-label={['태어난 년도','태어난 월','태어난 일'][i]} type="number" inputMode="numeric" required min={i===0?1900:1} max={i===0?2050:i===1?12:31} placeholder={['YYYY','MM','DD'][i]} value={birth[key]} onChange={v=>setBirth({...birth,[key]:v.target.value})}/><span>{['년','월','일'][i]}</span></label>)}</div>{detailed&&<BirthOptions profile={birth} onChange={setBirth}/>}<button disabled={!e.ready} className="button primary" type="submit">나의 사주 확인하기<ArrowRight size={18}/></button>{error&&<p className="error" role="alert">{error}</p>}<p className="privacy"><LockKeyhole size={13}/>입력 정보는 이 브라우저에만 저장돼요.</p></form>}
