"use client";
import {persistCalculated,profileResult} from '@/lib/saju/client';

import {createContext,useContext,useEffect,useState,useCallback, type ReactNode} from 'react';
import {dateKey} from '@/data/content';
import {emptyProfile,getDaily,type Profile} from '@/data/daily';
type PracticeRecord={done:boolean;note:string;mission:string;area:string};
type ViewRecord={score:number;mood:string;mission:string};
type ExerciseRecord={category:string;seconds:number;completedAt:string};
type Store={userProfile:Profile;dailyViews:Record<string,ViewRecord>;practiceRecords:Record<string,PracticeRecord>;exerciseRecords:Record<string,ExerciseRecord[]>;savedQuotes:number[]};
const blank:Store={userProfile:emptyProfile,dailyViews:{},practiceRecords:{},exerciseRecords:{},savedQuotes:[]};
const keys=Object.keys(blank) as (keyof Store)[];
function read(key:string,fallback:unknown){try{const v=localStorage.getItem(key);return v?JSON.parse(v):fallback}catch{return fallback}}
function object(v:unknown):v is Record<string,unknown>{return !!v&&typeof v==='object'&&!Array.isArray(v)}
function hydrate():Store{const p=read('userProfile',read('energy-birth',{}));const profile={...emptyProfile};if(object(p)){for(const k of ['nickname','year','month','day','hour','minute','timezone'] as const)if(typeof p[k]==='string')profile[k]=p[k] as string;profile.calendar=p.calendar==='lunar'?'lunar':'solar';profile.reminder=p.reminder===true;profile.leapMonth=p.leapMonth===true;profile.dayBoundary=p.dayBoundary==='zi23'?'zi23':'midnight'}const records=read('practiceRecords',read('energy-practice',{}));const practiceRecords:Store['practiceRecords']={};if(object(records))for(const [k,v]of Object.entries(records)){if(/^\d{4}-\d{2}-\d{2}$/.test(k)&&object(v)&&typeof v.note==='string')practiceRecords[k]={done:v.done===true,note:v.note,mission:typeof v.mission==='string'?v.mission:'이전 실천',area:typeof v.area==='string'?v.area:'이전 기록'}}const views=read('dailyViews',{});const dailyViews:Store['dailyViews']={};if(object(views))for(const[k,v]of Object.entries(views)){if(object(v)&&typeof v.score==='number'&&typeof v.mood==='string'&&typeof v.mission==='string')dailyViews[k]=v as ViewRecord}const exercises=read('exerciseRecords',{});const exerciseRecords:Store['exerciseRecords']={};if(object(exercises))for(const[k,v]of Object.entries(exercises)){if(Array.isArray(v))exerciseRecords[k]=v.filter(x=>object(x)&&typeof x.category==='string'&&typeof x.seconds==='number'&&typeof x.completedAt==='string') as ExerciseRecord[]}const saved=read('savedQuotes',read('energy-quotes',[]));return {userProfile:profile,practiceRecords,dailyViews,exerciseRecords,savedQuotes:Array.isArray(saved)?saved.filter(x=>Number.isInteger(x)&&x>=0&&x<10):[]};}
type Context=Store & {ready:boolean;today:string;error:string;saveProfile:(p:Profile)=>boolean;savePractice:(record:PracticeRecord)=>boolean;recordExercise:(category:string)=>boolean;toggleQuote:(id:number)=>boolean;clearData:()=>boolean};
const EnergyContext=createContext<Context|null>(null);
export function EnergyProvider({children}:{children:ReactNode}){const [state,setState]=useState<Store>(blank);const [ready,setReady]=useState(false);const [today,setToday]=useState('');const [error,setError]=useState('');
useEffect(()=>{const stored=hydrate();const day=dateKey();const d=persistCalculated(stored.userProfile,day);const view={score:d.score,mood:d.mood,mission:d.mission.title};if(!stored.dailyViews[day])stored.dailyViews[day]=view;try{for(const k of keys)localStorage.setItem(k,JSON.stringify(stored[k]));}catch{setError('이 브라우저에서 기록을 저장할 수 없어요. 저장 권한을 확인해주세요.')}setState(stored);setToday(day);setReady(true);
const refresh=()=>{setState(hydrate());setToday(dateKey())};window.addEventListener('storage',refresh);const rollover=()=>{if(dateKey()!==day){const next=hydrate();const key=dateKey();const daily=persistCalculated(next.userProfile,key);if(!next.dailyViews[key]){next.dailyViews[key]={score:daily.score,mood:daily.mood,mission:daily.mission.title};try{localStorage.setItem('dailyViews',JSON.stringify(next.dailyViews))}catch{}}setState(next);setToday(key)}};const timer=setInterval(rollover,60000);document.addEventListener('visibilitychange',rollover);return()=>{clearInterval(timer);window.removeEventListener('storage',refresh);document.removeEventListener('visibilitychange',rollover)};},[]);
const commit=useCallback(<K extends keyof Store>(key:K,value:Store[K])=>{try{localStorage.setItem(key,JSON.stringify(value));setState(s=>({...s,[key]:value}));setError('');return true}catch{setError('저장하지 못했어요. 브라우저 저장 권한을 확인해주세요.');return false}},[]);
const saveProfile=(p:Profile)=>{try{profileResult(p)}catch(err){setError((err as Error).message);return false}if(!commit('userProfile',p))return false;const d=persistCalculated(p,today||dateKey());commit('dailyViews',{...state.dailyViews,[today]:{score:d.score,mood:d.mood,mission:d.mission.title}});return true};
const savePractice=(record:PracticeRecord)=>commit('practiceRecords',{...state.practiceRecords,[today]:record});
const recordExercise=(category:string)=>commit('exerciseRecords',{...state.exerciseRecords,[dateKey()]:[...(state.exerciseRecords[dateKey()]||[]),{category,seconds:300,completedAt:new Date().toISOString()}]});
const toggleQuote=(id:number)=>commit('savedQuotes',state.savedQuotes.includes(id)?state.savedQuotes.filter(x=>x!==id):[...state.savedQuotes,id]);
const clearData=()=>{try{for(const k of [...keys,'energy-birth','energy-practice','energy-quotes','sajuProfile',...Object.keys(localStorage).filter(k=>k.startsWith('dailyData_'))])localStorage.removeItem(k);setState(blank);setError('');return true}catch{setError('일부 데이터를 삭제하지 못했어요.');return false}};
return <EnergyContext.Provider value={{...state,ready,today,error,saveProfile,savePractice,recordExercise,toggleQuote,clearData}}>{children}{error&&<div className="storage-alert" role="alert">{error}</div>}</EnergyContext.Provider>}
export function useEnergy(){const value=useContext(EnergyContext);if(!value)throw new Error('EnergyProvider missing');return value;}
