"use client";
import Link from 'next/link';
import { usePathname } from 'next/navigation';
import { useState } from 'react';
import { MoonStar, Menu, X, Search, UserRound, ArrowUpRight } from 'lucide-react';
export const links = [['/','홈'],['/today','오늘의 나'],['/saju','나의 사주'],['/cheongan-jiji','천간지지'],['/practice','오늘 한 가지 실천'],['/quote','오늘의 명언'],['/exercise','5분 운동']];
export function Header(){const path=usePathname(); const [open,setOpen]=useState(false); const [search,setSearch]=useState(false); const [query,setQuery]=useState('');return <header className="header"><div className="header-inner"><Link href="/" className="brand"><MoonStar size={26}/><span>오늘의 기운</span></Link><nav className={open?'nav open':'nav'} aria-label="주 메뉴">{links.map(([url,label])=><Link key={url} href={url} className={path===url?'active':''} onClick={()=>setOpen(false)}>{label}</Link>)}<Link className="mobile-extra" href="/my-record" onClick={()=>setOpen(false)}>나의 기록</Link><Link className="mobile-extra" href="/mypage" onClick={()=>setOpen(false)}>마이페이지</Link></nav><div className="header-tools"><button className="icon-button" aria-label="페이지 검색" onClick={()=>setSearch(!search)}><Search size={19}/></button><Link className="icon-button" aria-label="마이페이지" href="/mypage"><UserRound size={19}/></Link><Link className="header-cta" href="/practice">오늘도 좋은 하루 <span>✧</span></Link></div><button aria-label={open?'메뉴 닫기':'메뉴 열기'} aria-expanded={open} className="mobile-menu icon-button" onClick={()=>setOpen(!open)}>{open?<X/>:<Menu/>}</button></div>{search&&<div className="search-panel"><label htmlFor="search">어떤 기운을 찾으세요?</label><input id="search" autoFocus placeholder="사주, 명언, 운동…" value={query} onChange={e=>setQuery(e.target.value)}/><div>{links.filter(([,l])=>l.includes(query)).map(([u,l])=><Link href={u} key={u} onClick={()=>setSearch(false)}>{l} <ArrowUpRight size={16}/></Link>)}{!links.some(([,l])=>l.includes(query))&&<p>찾는 페이지가 없어요. 다른 단어로 검색해보세요.</p>}</div></div>}</header>}
export function Footer(){return <footer className="footer"><div className="container footer-top"><div><Link href="/" className="brand"><MoonStar size={25}/>오늘의 기운</Link><p>좋은 기운이, 좋은 하루를 만듭니다.</p></div><div className="footer-links">{[...links.slice(1),["/my-record","나의 기록"],["/mypage","마이페이지"]].map(([u,l])=><Link href={u} key={u}>{l}</Link>)}</div></div><div className="container footer-bottom"><span>© {new Date().getFullYear()} 오늘의 기운</span><span>당신의 일상에, 작은 빛 하나.</span></div></footer>}

