"use client";
import {useId} from 'react';
import Link from 'next/link';
import {ArrowRight,Check,Sun,ShieldCheck,Quote,Heart,BookOpen,Wallet,Activity,Smile,Sparkles} from 'lucide-react';
import {categories,flowMessages,getDaily,weekKeys,addDays,type Profile} from '@/data/daily';
import {useEnergy} from './EnergyStore';
export function CelestialHero({variant='home'}:{variant?:string}){return <div className={'celestial-art art-'+variant}><img src="/images/saju-celestial-hero.png" alt="달빛과 산, 호수를 바라보는 여성의 조용한 풍경"/></div>}
export function PageHero({title,description,eyebrow,variant='home',children}:{title:string;description:string;eyebrow:string;variant?:string;children?:React.ReactNode}){return <div className="rich-hero"><div className="rich-hero-copy"><p className="eyebrow">✧ &nbsp; {eyebrow}</p><h1>{title}</h1><p className="rich-description">{description}</p>{children}</div><CelestialHero variant={variant}/></div>}
export function ScoreRing({value,label,small=false}:{value:number;label?:string;small?:boolean}){return <div className={'score-ring '+(small?'small':'')} style={{'--score':`${value}%`} as React.CSSProperties} role="img" aria-label={`${label||'기운'} ${value}점`}><div>{label&&<span>{label}</span>}<strong>{value}<small>점</small></strong></div></div>}
export function SectionTitle({title,eyebrow,href,label='자세히 보기'}:{title:string;eyebrow?:string;href?:string;label?:string}){return <div className="section-title"><div>{eyebrow&&<p className="eyebrow">{eyebrow}</p>}<h2>{title}</h2></div>{href&&<Link href={href}>{label}<ArrowRight size={16}/></Link>}</div>}
export function NextAction({href,label}:{href:string;label:string}){return <div className="next-action"><Link className="button primary" href={href}>{label}<ArrowRight size={17}/></Link></div>}
export function SampleNote(){return <p className="sample-note">✧ 간지는 달력 계산값입니다. 점수와 해석은 자기성찰을 위한 규칙형 가이드이며 예측 확률이 아닙니다.</p>}
export function DailySummary(){const e=useEnergy();const d=getDaily(e.userProfile,e.today||'2026-09-15');let streak=0;if(e.today){let k=e.today;while(e.dailyViews[k]){streak++;k=addDays(k,-1)}}return <div className="daily-summary"><div className="summary-top"><h2>오늘의 나 요약</h2><span>나를 위한 하루 가이드</span></div><div className="summary-main"><ScoreRing value={d.score} label="오늘의 기운"/><p>{d.summary}</p></div><div className="mini-scores">{categories.map((c,i)=><span key={c}>{c}<strong>{d.scores[i]}</strong></span>)}</div><div className="summary-actions"><Link className="button primary" href="/today">오늘의 나 자세히 보기<ArrowRight size={16}/></Link><Link className="button secondary" href="/practice">오늘 한 가지 실천하기</Link></div><div className="streak"><Sparkles size={15}/>{streak}일 연속 확인 중 <span>{Array.from({length:7},(_,i)=><i key={i} className={i<Math.min(streak,7)?'filled':''}/>)}</span></div></div>}
export function GuideCards({home=false}:{home?:boolean}){const e=useEnergy();const d=getDaily(e.userProfile,e.today||'2026-09-15');return <div className="guide-grid">{[{title:'하면 좋은 일',Icon:Check,items:d.guide.goodThings},{title:home?'조심할 일':'피하면 좋은 일',Icon:ShieldCheck,items:d.guide.avoidThings},{title:home?'오늘의 한 줄 메시지':'조심할 일',Icon:Sun,items:d.guide.cautionThings}].map(({title,Icon,items},i)=><article className={'guide-card guide-'+i} key={title}><h3><Icon size={21}/>{title}</h3>{home&&i===2?<><blockquote>여유가 있는 마음이<br/>좋은 기회를 불러옵니다.</blockquote><Link href="/today#tomorrow">내일의 기운 살짝 보기 <ArrowRight size={15}/></Link></>:<ul>{items.slice(0,home?3:5).map(x=><li key={x}>{x}</li>)}</ul>}</article>)}</div>}
export function FortuneScores(){const e=useEnergy();const d=getDaily(e.userProfile,e.today||'2026-09-15');const icons=[Heart,BookOpen,Wallet,Activity,Smile];return <div className="fortune-grid">{categories.map((c,i)=>{const Icon=icons[i];return <article className="panel fortune-card" key={c}><h3><Icon size={18}/>{c}{i===1?'운':'운'}</h3><ScoreRing small value={d.scores[i]}/><p>{d.summaries[i]}</p></article>})}</div>}
export function WeeklyProgress({kind='practice',ring=false}:{kind?:'practice'|'visit'|'exercise';ring?:boolean}){const e=useEnergy();const week=e.today?weekKeys(e.today):[];const complete=(k:string)=>kind==='practice'?e.practiceRecords[k]?.done:kind==='visit'?!!e.dailyViews[k]:(e.exerciseRecords[k]?.length||0)>0;const count=week.filter(complete).length;return <div className="weekly-progress">{ring?<div className="weekly-ring" style={{'--score':`${count/7*100}%`} as React.CSSProperties}><strong>{count} / 7</strong><span>{Math.round(count/7*100)}%</span></div>:<div className="weekly-number"><strong>{count}</strong><span> / 7일</span></div>}<div className="week-days">{week.map((k,i)=><span key={k}>{['월','화','수','목','금','토','일'][i]}<i title={k} aria-label={complete(k)?'완료':'미완료'} className={'week-dot '+(complete(k)?'done':'')}>{complete(k)&&<Check size={14}/>}</i></span>)}</div></div>}
export function ElementBalance(){return <div className="element-balance">{[['목','木',25],['화','火',20],['토','土',30],['금','金',15],['수','水',10]].map(([name,han,value],i)=><div key={name} className={'element-'+i}><span>{han}</span><p>{name}</p><strong>{value}%</strong><div className="bar"><i style={{width:value+'%'}}/></div></div>)}</div>}
