import type {SajuProfile} from './buildSajuProfile';
import {calculateTodayPillar} from './calculateTodayPillar';
import {ELEMENTS,type Element} from './types';
import {library,missions} from '../../data/catalog';
const advice:Record<Element,string>={목:'작은 배움 하나 시작하기',화:'따뜻한 안부 전하기',토:'식사와 휴식 시간 챙기기',금:'미뤄둔 일 하나 정리하기',수:'조용히 생각할 시간 만들기'};
export function buildDaily(p:SajuProfile|null,date:string){const today=calculateTodayPillar(date,p?.birth.timezone);const source=p?.dayMaster?.element;const target=today.stem.element;const from=source?ELEMENTS.indexOf(source):-1,to=ELEMENTS.indexOf(target);const relation=from<0?'일반 안내':from===to?'같은 기운':(from+1)%5===to?'표현과 나눔':(to+1)%5===from?'도움을 받는 흐름':(from+2)%5===to?'계획과 관리':'속도 조절';const support=p?.elementInsight.weakest.includes(target)?3:0;const over=p&&p.fiveElements[target]>=38?-3:0;const harmony=source&&((to+1)%5===from||(from+1)%5===to)?5:0;const same=source===target?3:0;const polarity=p&&((p.yinYang.yang>50&&today.stem.yinYang==='음')||(p.yinYang.yin>50&&today.stem.yinYang==='양'))?2:0;const tension=source&&(to+2)%5===from?-5:0;
 const contributions={base:70,harmony,dayMaster:same+tension,supplement:support,excess:over,yinYang:polarity};
 const weights=[[1,1,1,1,1],[1,1.4,1,.8,.5],[.5,1,1,1,.5],[.5,.5,1,1.5,1.5],[1,.5,1,1,2]];
 const parts=[harmony,same+tension,support,over,polarity];const scores=weights.map(w=>Math.max(45,Math.min(95,Math.round(70+w.reduce((a,n,i)=>a+n*parts[i],0)))));const score=Math.round(scores.reduce((a,b)=>a+b,0)/5);
 const mood=over<0||tension<0?'균형':harmony>0?'성장':'차분함';const summary=p?`${today.stem.korean}${today.branch.korean}일, ${relation}을 생활의 힌트로 삼아보세요. ${advice[target]}.`:`${today.stem.korean}${today.branch.korean}일의 일반 가이드입니다. 생년월일을 입력하면 나의 구성과 연결해드려요.`;
 const mission=missions[mood==='균형'?3:mood==='성장'?4:to===1?2:to===3?0:5];const quote=library[mood==='균형'?5:mood==='성장'?0:to===1?7:3];const exercise=scores[3]<70?'숙면':mood==='균형'?'목·어깨':'전신';
 const summaries=[`${relation}을 참고해 상대의 이야기를 먼저 들어보세요.`,`${advice[target]}. 한 번에 한 가지에 집중해보세요.`,'소비 결정을 내리기 전 예산과 필요를 확인해보세요.','컨디션은 직접 살펴보고 편안한 범위에서 움직여보세요.',`${mood}을 떠올리며 지금의 감정을 짧게 적어보세요.`];const guide={goodThings:[advice[target],mission.title,'가까운 사람의 이야기 끝까지 듣기'],avoidThings:['감정이 앞서는 말','즉흥적으로 채운 일정'],cautionThings:[over<0?'익숙한 방식만 고집하기':'다른 사람과 속도 비교하기','휴식 없이 오래 집중하기']};
 const interaction={overallScore:score,summary,keywords:[mood,relation],relationship:{score:scores[0],summary:summaries[0]},workStudy:{score:scores[1],summary:summaries[1]},money:{score:scores[2],summary:summaries[2]},health:{score:scores[3],summary:summaries[3]},emotion:{score:scores[4],summary:summaries[4]}};
 return {today,interaction,guide,practice:{...mission,category:mission.area},quote:{...quote,reason:`오늘의 '${mood}' 키워드와 '${relation}'을 떠올리며 고른 자체 문장입니다.`},exercise:{category:exercise,title:`5분 ${exercise} 스트레칭`},contributions,weights,score,scores,summary,summaries,mission,mood,isMock:false,isPersonalized:!!p?.dayMaster};}
